--SELECTION QUERY FOR SALES_ORDER
SELECT INVENTORY_ITEM_ID                   
|| ',' ||ORGANIZATION_ID                     
|| ',' ||DEMAND_ID                           
|| ',' ||PRIMARY_UOM_QUANTITY                
|| ',' ||RESERVATION_TYPE                    
|| ',' ||RESERVATION_QUANTITY                
|| ',' ||DEMAND_SOURCE_TYPE                  
|| ',' ||DEMAND_SOURCE_HEADER_ID             
|| ',' ||COMPLETED_QUANTITY                  
|| ',' ||SUBINVENTORY                        
|| ',' ||DEMAND_CLASS                        
|| ',' ||REQUIREMENT_DATE                    
|| ',' ||DEMAND_SOURCE_LINE                  
|| ',' ||DEMAND_SOURCE_DELIVERY              
|| ',' ||DEMAND_SOURCE_NAME                  
|| ',' ||PARENT_DEMAND_ID                    
|| ',' ||DELETED_FLAG                        
|| ',' ||LAST_UPDATE_DATE                    
|| ',' ||LAST_UPDATED_BY                     
|| ',' ||CREATION_DATE                       
|| ',' ||CREATED_BY                          
|| ',' ||LAST_UPDATE_LOGIN                   
|| ',' ||REQUEST_ID                          
|| ',' ||PROGRAM_APPLICATION_ID              
|| ',' ||PROGRAM_ID                          
|| ',' ||PROGRAM_UPDATE_DATE                 
|| ',' ||REFRESH_ID                          
|| ',' ||SR_INSTANCE_ID                      
|| ',' ||SALES_ORDER_NUMBER                  
|| ',' ||SALESREP_CONTACT                    
|| ',' ||ORDERED_ITEM_ID                     
|| ',' ||AVAILABLE_TO_MRP                    
|| ',' ||CUSTOMER_ID                         
|| ',' ||SHIP_TO_SITE_USE_ID                 
|| ',' ||BILL_TO_SITE_USE_ID                 
|| ',' ||LINE_NUM                            
|| ',' ||TERRITORY_ID                        
|| ',' ||UPDATE_SEQ_NUM                      
|| ',' ||DEMAND_TYPE                         
|| ',' ||PROJECT_ID                          
|| ',' ||TASK_ID                             
|| ',' ||PLANNING_GROUP                      
|| ',' ||END_ITEM_UNIT_NUMBER                
|| ',' ||DEMAND_PRIORITY                     
|| ',' ||ATP_REFRESH_NUMBER                  
|| ',' ||REQUEST_DATE                        
|| ',' ||SELLING_PRICE                       
|| ',' ||DEMAND_VISIBLE                      
|| ',' ||FORECAST_VISIBLE                    
|| ',' ||CTO_FLAG                            
|| ',' ||ORIGINAL_SYSTEM_REFERENCE           
|| ',' ||ORIGINAL_SYSTEM_LINE_REFERENCE      
|| ',' ||COMPANY_ID                          
|| ',' ||COMPANY_NAME                        
|| ',' ||ITEM_NAME                           
|| ',' ||ORDERED_ITEM_NAME                   
|| ',' ||CUSTOMER_NAME                       
|| ',' ||SHIP_TO_SITE_CODE                   
|| ',' ||BILL_TO_SITE_CODE                   
|| ',' ||ORGANIZATION_CODE                   
|| ',' ||SR_INSTANCE_CODE                    
|| ',' ||PROJECT_NUMBER                      
|| ',' ||TASK_NUMBER                         
|| ',' ||MESSAGE_ID                          
|| ',' ||PROCESS_FLAG                        
|| ',' ||BATCH_ID                            
|| ',' ||DATA_SOURCE_TYPE                    
|| ',' ||ST_TRANSACTION_ID                   
|| ',' ||ERROR_TEXT                          
|| ',' ||COMMENTS                            
|| ',' ||ORDER_RELEASE_NUMBER                
|| ',' ||END_ORDER_NUMBER                    
|| ',' ||END_ORDER_RELEASE_NUMBER            
|| ',' ||END_ORDER_LINE_NUMBER               
|| ',' ||END_ORDER_TYPE                      
|| ',' ||NEW_ORDER_PLACEMENT_DATE            
|| ',' ||ORIGINAL_ITEM_ID                    
|| ',' ||PROMISE_DATE                        
|| ',' ||ORIGINAL_ITEM_NAME                  
|| ',' ||LINK_TO_LINE_ID                     
|| ',' ||CUST_PO_NUMBER                      
|| ',' ||CUSTOMER_LINE_NUMBER                
|| ',' ||MFG_LEAD_TIME                       
|| ',' ||ORDER_DATE_TYPE_CODE                
|| ',' ||LATEST_ACCEPTABLE_DATE              
|| ',' ||SHIPPING_METHOD_CODE                
|| ',' ||SCHEDULE_ARRIVAL_DATE               
|| ',' ||ORG_FIRM_FLAG                       
|| ',' ||SHIP_SET_ID                         
|| ',' ||ARRIVAL_SET_ID                      
|| ',' ||SOURCE_DEMAND_SOURCE_HEADER_ID      
|| ',' ||SOURCE_ORGANIZATION_ID              
|| ',' ||SOURCE_ORIGINAL_ITEM_ID             
|| ',' ||SOURCE_DEMAND_ID                    
|| ',' ||SOURCE_INVENTORY_ITEM_ID            
|| ',' ||SOURCE_CUSTOMER_ID                  
|| ',' ||SOURCE_BILL_TO_SITE_USE_ID          
|| ',' ||SOURCE_SHIP_TO_SITE_USE_ID          
|| ',' ||ATO_LINE_ID                         
|| ',' ||SHIP_SET_NAME                       
|| ',' ||ARRIVAL_SET_NAME                    
|| ',' ||SALESREP_ID                         
|| ',' ||INTRANSIT_LEAD_TIME                 
|| ',' ||SOURCE_DEMAND_SOURCE_LINE           
|| ',' ||ROW_TYPE                            
|| ',' ||REVISED_DMD_DATE                    
|| ',' ||REVISED_DMD_PRIORITY                
|| ',' ||ITEM_TYPE_ID                        
|| ',' ||ITEM_TYPE_VALUE     SALES_ORDERS_TABLE
from msc_st_sales_orders where process_flag = 3;  

DAPAT where_clause := 'process_flag = 3 AND TRUNC(creation_date) = TRUNC(SYSDATE) AND abs(request_id) >= '||v_main_request_id;                