--SELECTION QUERY FOR WIP
SELECT ORDER_PRIORITY                      
|| ',' ||DEMAND_ID                           
|| ',' ||INVENTORY_ITEM_ID                   
|| ',' ||ORGANIZATION_ID                     
|| ',' ||USING_ASSEMBLY_ITEM_ID              
|| ',' ||USING_ASSEMBLY_DEMAND_DATE          
|| ',' ||USING_REQUIREMENT_QUANTITY          
|| ',' ||ASSEMBLY_DEMAND_COMP_DATE           
|| ',' ||DEMAND_TYPE                         
|| ',' ||DAILY_DEMAND_RATE                   
|| ',' ||ORIGINATION_TYPE                    
|| ',' ||SOURCE_ORGANIZATION_ID              
|| ',' ||DISPOSITION_ID                      
|| ',' ||RESERVATION_ID                      
|| ',' ||DEMAND_SCHEDULE_NAME                
|| ',' ||PROJECT_ID                          
|| ',' ||TASK_ID                             
|| ',' ||PLANNING_GROUP                      
|| ',' ||END_ITEM_UNIT_NUMBER                
|| ',' ||SCHEDULE_DATE                       
|| ',' ||OPERATION_SEQ_NUM                   
|| ',' ||QUANTITY_ISSUED                     
|| ',' ||DEMAND_CLASS                        
|| ',' ||SALES_ORDER_NUMBER                  
|| ',' ||SALES_ORDER_PRIORITY                
|| ',' ||FORECAST_PRIORITY                   
|| ',' ||MPS_DATE_REQUIRED                   
|| ',' ||PO_NUMBER                           
|| ',' ||WIP_ENTITY_NAME                     
|| ',' ||DELETED_FLAG                        
|| ',' ||LAST_UPDATE_DATE                    
|| ',' ||LAST_UPDATED_BY                     
|| ',' ||CREATION_DATE                       
|| ',' ||CREATED_BY                          
|| ',' ||LAST_UPDATE_LOGIN                   
|| ',' ||REQUEST_ID                          
|| ',' ||PROGRAM_APPLICATION_ID              
|| ',' ||PROGRAM_ID                          
|| ',' ||PROGRAM_UPDATE_DATE                 
|| ',' ||SR_INSTANCE_ID                      
|| ',' ||REFRESH_ID                          
|| ',' ||REPETITIVE_SCHEDULE_ID              
|| ',' ||WIP_ENTITY_ID                       
|| ',' ||SELLING_PRICE                       
|| ',' ||DMD_LATENESS_COST                   
|| ',' ||DMD_SATISFIED_DATE                  
|| ',' ||DMD_SPLIT_FLAG                      
|| ',' ||REQUEST_DATE                        
|| ',' ||ORDER_NUMBER                        
|| ',' ||WIP_STATUS_CODE                     
|| ',' ||WIP_SUPPLY_TYPE                     
|| ',' ||ATTRIBUTE1                          
|| ',' ||ATTRIBUTE2                          
|| ',' ||ATTRIBUTE3                          
|| ',' ||ATTRIBUTE4                          
|| ',' ||ATTRIBUTE5                          
|| ',' ||ATTRIBUTE6                          
|| ',' ||ATTRIBUTE7                          
|| ',' ||ATTRIBUTE8                          
|| ',' ||ATTRIBUTE9                          
|| ',' ||ATTRIBUTE10                         
|| ',' ||ATTRIBUTE11                         
|| ',' ||ATTRIBUTE12                         
|| ',' ||ATTRIBUTE13                         
|| ',' ||ATTRIBUTE14                         
|| ',' ||ATTRIBUTE15                         
|| ',' ||SALES_ORDER_LINE_ID                 
|| ',' ||CONFIDENCE_PERCENTAGE               
|| ',' ||BUCKET_TYPE                         
|| ',' ||BILL_ID                             
|| ',' ||CUSTOMER_ID                         
|| ',' ||PROBABILITY                         
|| ',' ||SERVICE_LEVEL                       
|| ',' ||FORECAST_MAD                        
|| ',' ||FORECAST_DESIGNATOR                 
|| ',' ||ORIGINAL_SYSTEM_REFERENCE           
|| ',' ||ORIGINAL_SYSTEM_LINE_REFERENCE      
|| ',' ||DEMAND_SOURCE_TYPE                  
|| ',' ||SHIP_TO_SITE_ID                     
|| ',' ||COMPANY_ID                          
|| ',' ||COMPANY_NAME                        
|| ',' ||CUSTOMER_NAME                       
|| ',' ||CUSTOMER_SITE_ID                    
|| ',' ||CUSTOMER_SITE_CODE                  
|| ',' ||BILL_CODE                           
|| ',' ||ITEM_NAME                           
|| ',' ||ROUTING_NAME                        
|| ',' ||ALTERNATE_ROUTING_DESIGNATOR        
|| ',' ||OPERATION_EFFECTIVITY_DATE          
|| ',' ||USING_ASSEMBLY_ITEM_NAME            
|| ',' ||PROJECT_NUMBER                      
|| ',' ||TASK_NUMBER                         
|| ',' ||SCHEDULE_LINE_NUM                   
|| ',' ||OPERATION_SEQ_CODE                  
|| ',' ||ORGANIZATION_CODE                   
|| ',' ||SR_INSTANCE_CODE                    
|| ',' ||MESSAGE_ID                          
|| ',' ||PROCESS_FLAG                        
|| ',' ||BATCH_ID                            
|| ',' ||DATA_SOURCE_TYPE                    
|| ',' ||ST_TRANSACTION_ID                   
|| ',' ||ERROR_TEXT                          
|| ',' ||COMMENTS                            
|| ',' ||PROMISE_DATE                        
|| ',' ||LINK_TO_LINE_ID                     
|| ',' ||QUANTITY_PER_ASSEMBLY               
|| ',' ||ORDER_DATE_TYPE_CODE                
|| ',' ||LATEST_ACCEPTABLE_DATE              
|| ',' ||SHIPPING_METHOD_CODE                
|| ',' ||SCHEDULE_SHIP_DATE                  
|| ',' ||SCHEDULE_ARRIVAL_DATE               
|| ',' ||REQUEST_SHIP_DATE                   
|| ',' ||PROMISE_SHIP_DATE                   
|| ',' ||SOURCE_ORG_ID                       
|| ',' ||SOURCE_INVENTORY_ITEM_ID            
|| ',' ||SOURCE_USING_ASSEMBLY_ITEM_ID       
|| ',' ||SOURCE_SALES_ORDER_LINE_ID          
|| ',' ||SOURCE_PROJECT_ID                   
|| ',' ||SOURCE_TASK_ID                      
|| ',' ||SOURCE_CUSTOMER_SITE_ID             
|| ',' ||SOURCE_BILL_ID                      
|| ',' ||SOURCE_DISPOSITION_ID               
|| ',' ||SOURCE_CUSTOMER_ID                  
|| ',' ||SOURCE_OPERATION_SEQ_NUM            
|| ',' ||SOURCE_WIP_ENTITY_ID                
|| ',' ||ROUTING_SEQUENCE_ID                 
|| ',' ||ASSET_SERIAL_NUMBER                 
|| ',' ||ASSET_ITEM_ID                       
|| ',' ||COMPONENT_SCALING_TYPE              
|| ',' ||COMPONENT_YIELD_FACTOR              
|| ',' ||ITEM_TYPE_ID                        
|| ',' ||ITEM_TYPE_VALUE                     
|| ',' ||REPAIR_LINE_ID                      
|| ',' ||RO_STATUS_CODE                      
|| ',' ||REPAIR_NUMBER                       
|| ',' ||ENTITY                              
|| ',' ||REVISED_DMD_DATE                    
|| ',' ||REVISED_DMD_PRIORITY                
|| ',' ||SCHEDULE_DESIGNATOR_ID              
|| ',' ||OBJECT_TYPE                         
|| ',' ||OPERATING_FLEET                     
|| ',' ||MAINTENANCE_REQUIREMENT             
|| ',' ||CLASS_CODE                          
|| ',' ||MAINTENANCE_OBJECT_SOURCE   WIP_TABLE
from msc_st_demands where process_flag = 3;

DAPAT where_clause := process_flag = 3 AND TRUNC(creation_date) = TRUNC(SYSDATE) AND abs(request_id) >= '||v_main_request_id;        